'use client';

import { useState, useEffect } from 'react';
import { Database } from '../database/database';
import { useUser } from '../context/UserContext';

export default function PrintableRecords() {
  const [detections, setDetections] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const { user } = useUser();

  useEffect(() => {
    async function fetchData() {
      if (!user) return;

      try {
        setLoading(true);
        // Get all animal reports for this user
        const userReports = Database.getAnimalReportsByUserId(user.id);
        setDetections(userReports || []);
      } catch (error) {
        console.error("Error fetching reports:", error);
      } finally {
        setLoading(false);
      }
    }

    fetchData();
  }, [user]);

  const handlePrint = () => {
    window.print();
  };

  if (!user) {
    return <div className="p-8 text-center">Please log in to view your detection records.</div>;
  }

  return (
    <div className="container mx-auto p-6 max-w-4xl">
      {/* This section won't be printed */}
      <div className="print:hidden mb-8">
        <h1 className="text-3xl font-bold mb-4">Your Animal Detection Records</h1>
        <p className="mb-4 text-gray-600">
          This page displays all your animal detection records. Click the button below to print your records or save as PDF.
        </p>
        <button 
          onClick={handlePrint}
          className="bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded transition-colors"
        >
          Print Records
        </button>
      </div>

      {/* Printable content */}
      <div className="bg-white shadow-md rounded-lg p-6 print:shadow-none print:p-0">
        {/* Header that appears in print */}
        <div className="hidden print:block mb-8">
          <h1 className="text-2xl font-bold text-center">Animal Detection Records</h1>
          <p className="text-center text-gray-600">User: {user.name} ({user.email})</p>
          <p className="text-center text-gray-600">Date: {new Date().toLocaleDateString()}</p>
        </div>

        {loading ? (
          <div className="text-center py-8">Loading your records...</div>
        ) : detections.length === 0 ? (
          <div className="text-center py-8 text-gray-600">You don't have any animal detection records yet.</div>
        ) : (
          <div>
            <table className="w-full border-collapse">
              <thead>
                <tr className="border-b-2 border-gray-200">
                  <th className="text-left py-3 px-4">Date</th>
                  <th className="text-left py-3 px-4">Animal Type</th>
                  <th className="text-left py-3 px-4">Endangered</th>
                  <th className="text-left py-3 px-4">Notes</th>
                </tr>
              </thead>
              <tbody>
                {detections.map((detection, index) => (
                  <tr key={index} className="border-b border-gray-100">
                    <td className="py-3 px-4">{new Date(detection.date).toLocaleDateString()}</td>
                    <td className="py-3 px-4 capitalize">{detection.animalType}</td>
                    <td className="py-3 px-4">{detection.isEndangered ? 'Yes' : 'No'}</td>
                    <td className="py-3 px-4">{detection.notes}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            
            <div className="mt-8 text-center text-gray-500 text-sm print:mt-16 print:pt-8 print:border-t print:border-gray-200">
              <p>Generated by Wildlife Detection System</p>
              <p>This report contains verified animal detections from our AI-powered system.</p>
            </div>
          </div>
        )}
      </div>

      {/* Print styles */}
      <style jsx global>{`
        @media print {
          body {
            font-size: 12pt;
            color: #000;
          }
          
          @page {
            margin: 2cm;
          }
        }
      `}</style>
    </div>
  );
} 